## Word Embedding

In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [88]:
data = {
    'text' : ['People Watch Facebook','Facebook watch facebook','People write comments','Facebook write comments'],
    'output': [1,1,0,0,]
}
df = pd.DataFrame(data)
df

text  output
0    People Watch Facebook       1
1  Facebook watch facebook       1
2    People write comments       0
3  Facebook write comments       0

In [89]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [90]:
#Bag of Words (Bow)
bow = cv.fit_transform(df['text'])

In [91]:
feature_names = cv.get_feature_names_out()
print(feature_names)

['comments' 'facebook' 'people' 'watch' 'write']


In [92]:
print(cv.vocabulary_) #Integers after strings  are the index value

{'people': 2, 'watch': 3, 'facebook': 1, 'write': 4, 'comments': 0}


In [93]:
#Checking BoW for sentence 1:
print(bow[0].toarray())

[[0 1 1 1 0]]


 Output: [[0 1 1 1 0]] : Thus Facebook People Watch

In [94]:
#  Converting all sentences toaraay
X = bow.toarray()
print(X)

[[0 1 1 1 0]
 [0 2 0 1 0]
 [1 0 1 0 1]
 [1 1 0 0 1]]


In [95]:
#Let's Change Binary parameter of CountVectorizer , To get only True and false value. Else it gives us frequency of a word in that particular sentence in matrix
cv2 = CountVectorizer(binary=True,lowercase=True, stop_words=None) #for optimal vocublary we can use these lowercase, stopwords parameters
bow2 = cv2.fit_transform(df['text'])
print(cv2.vocabulary_)
#  Converting all sentences toaraay
X2 = bow2.toarray()
print(X2)


{'people': 2, 'watch': 3, 'facebook': 1, 'write': 4, 'comments': 0}
[[0 1 1 1 0]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [1 1 0 0 1]]


In [96]:
#using N-gram parameter: (by default is (1,1))
cv3 = CountVectorizer(binary=True,lowercase=True, stop_words=None, ngram_range=(1,3)) #(2,2), (1,3), (1,2)
bow3 = cv3.fit_transform(df['text'])
print(cv3.vocabulary_)


{'people': 6, 'watch': 11, 'facebook': 1, 'people watch': 7, 'watch facebook': 12, 'people watch facebook': 8, 'facebook watch': 2, 'facebook watch facebook': 3, 'write': 13, 'comments': 0, 'people write': 9, 'write comments': 14, 'people write comments': 10, 'facebook write': 4, 'facebook write comments': 5}


In [97]:
#Converting all sentences toaraay
X3 = bow3.toarray()
print(X3)

[[0 1 0 0 0 0 1 1 1 0 0 1 1 0 0]
 [0 1 1 1 0 0 0 0 0 0 0 1 1 0 0]
 [1 0 0 0 0 0 1 0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0 0 0 0 0 0 1 1]]


In [98]:
cv.transform(['Facebook watch your comments']).toarray() #here they have ignored "your"

array([[1, 1, 0, 1, 0]])

### One Hot enchoder

In [99]:
#one hot encoder
from sklearn.preprocessing import OneHotEncoder 

In [100]:
ohe = OneHotEncoder()
one_hot_encoded = ohe.fit_transform(df[["text"]]) # By using df[["anything"]] 1D can be converted to 2D

In [101]:
print(one_hot_encoded)
col = ohe.get_feature_names_out(['text'])
print(col)
cat = ohe.categories_
print(cat)


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 4)>
  Coords	Values
  (0, 2)	1.0
  (1, 0)	1.0
  (2, 3)	1.0
  (3, 1)	1.0
['text_Facebook watch facebook' 'text_Facebook write comments'
 'text_People Watch Facebook' 'text_People write comments']
[array(['Facebook watch facebook', 'Facebook write comments',
       'People Watch Facebook', 'People write comments'], dtype=object)]


In [102]:
arr = one_hot_encoded.toarray()
df1 = pd.DataFrame(arr, columns=cat)
df2 = pd.concat([df, df1], axis=1)
df2

text  output  (Facebook watch facebook,)  \
0    People Watch Facebook       1                         0.0   
1  Facebook watch facebook       1                         1.0   
2    People write comments       0                         0.0   
3  Facebook write comments       0                         0.0   

   (Facebook write comments,)  (People Watch Facebook,)  \
0                         0.0                       1.0   
1                         0.0                       0.0   
2                         0.0                       0.0   
3                         1.0                       0.0   

   (People write comments,)  
0                       0.0  
1                       0.0  
2                       1.0  
3                       0.0

In [122]:
!pip install gensim

  Using cached gensim-4.3.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (8.1 kB)
  Using cached scipy-1.13.1-cp312-cp312-macosx_12_0_arm64.whl.metadata (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 11.9 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.4/30.4 MB 15.0 MB/s eta 0:00:0000:0100:01
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.0
    Uninstalling scipy-1.14.0:
      Successfully uninstalled scipy-1.14.0


In [124]:
import gensim
from gensim import models

In [125]:
import gensim.downloader as api

In [126]:

wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [127]:
vec_cricket = wv['cricket'] #it will have 300 values as 300 dimensions
vec_cricket

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [128]:
vec_cricket.shape

(300,)

In [166]:
wv.most_similar('Google')

[('Google_Nasdaq_GOOG', 0.7819362878799438),
 ('Google_GOOG', 0.7756521105766296),
 ('Google_NASDAQ_GOOG', 0.7557772994041443),
 ('Google_NSDQ_GOOG', 0.7538513541221619),
 ('Yahoo', 0.7491979598999023),
 ('GoogleGoogle', 0.7281472682952881),
 ('search_engine', 0.7255110144615173),
 ('Google_nasdaq_GOOG', 0.7014852166175842),
 ('Baidu', 0.6993466019630432),
 ('NASDAQ_GOOG', 0.6812566518783569)]

In [168]:
wv.most_similar('AI')

[('Steven_Spielberg_Artificial_Intelligence', 0.5575934052467346),
 ('Index_MDE_##/###/####', 0.5415324568748474),
 ('Enemy_AI', 0.5256390571594238),
 ('Ace_Combat_Zero', 0.522663414478302),
 ('DOA4', 0.5182536840438843),
 ('mechs', 0.5137375593185425),
 ('mech', 0.5077533721923828),
 ('playstyle', 0.5072520971298218),
 ('AI_bots', 0.5051203370094299),
 ('deathmatch_mode', 0.504591703414917)]

In [169]:
wv.most_similar('Artificial_Intelligence')

[('artificial_intelligence', 0.7004302144050598),
 ('USA_Subjex_Corporation', 0.5363693833351135),
 ('Artificial_Intelligence_AI', 0.52828049659729),
 ('Novamente', 0.52488112449646),
 ('Computational_Intelligence', 0.5138623118400574),
 ('Ben_Goertzel', 0.5136528611183167),
 ('Bot_Colony', 0.5046637058258057),
 ('Artificial_Intelligence_AAAI', 0.5035207867622375),
 ('Information_Retrieval', 0.5031781792640686),
 ('Neuroeconomics', 0.49684688448905945)]

In [170]:
wv.most_similar('Hitler')

[('Adolf_Hitler', 0.8693075180053711),
 ('Adolph_Hitler', 0.8060617446899414),
 ('Nazis', 0.7699975371360779),
 ('Nazi', 0.7654680609703064),
 ('Hilter', 0.7460282444953918),
 ('Third_Reich', 0.7436984777450562),
 ('Nazi_Germany', 0.7407962083816528),
 ('Führer', 0.716090202331543),
 ('Nazism', 0.6866580247879028),
 ('Goebbels', 0.6627063155174255)]

In [171]:
wv.most_similar('jews')

[('arabs', 0.703646183013916),
 ('jewish', 0.6818789839744568),
 ('Jews', 0.6657212972640991),
 ('muslims', 0.662420392036438),
 ('palestinians', 0.6185414791107178),
 ('zionists', 0.6171693801879883),
 ('palestine', 0.6166346073150635),
 ('jew', 0.6068050861358643),
 ('pakistanis', 0.6040884852409363),
 ('kikes', 0.6004521250724792)]

In [173]:
wv.most_similar('brain')

[('brains', 0.7413849830627441),
 ('frontal_lobe', 0.718148410320282),
 ('cerebellum', 0.698017418384552),
 ('cerebral_cortex', 0.6879504323005676),
 ('temporal_lobe', 0.658434271812439),
 ('cortex', 0.6564251780509949),
 ('brainstem', 0.6540578603744507),
 ('frontal_lobes', 0.6527895331382751),
 ('neural', 0.650603175163269),
 ('brain_frontal_lobe', 0.6460928916931152)]

In [129]:
wv.most_similar('cricket')

[('cricketing', 0.8372224569320679),
 ('cricketers', 0.8165745139122009),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [130]:
wv.most_similar('facebook')

[('Facebook', 0.7563532590866089),
 ('FaceBook', 0.7076999545097351),
 ('twitter', 0.6988552212715149),
 ('myspace', 0.6941817998886108),
 ('Twitter', 0.664244532585144),
 ('twitter_facebook', 0.6572229862213135),
 ('Facebook.com', 0.6529868245124817),
 ('myspace_facebook', 0.6370643973350525),
 ('facebook_twitter', 0.6367617845535278),
 ('linkedin', 0.6356593370437622)]

In [131]:
wv.most_similar('om')

[('på', 0.6145849823951721),
 ('aan', 0.61150723695755),
 ('ter', 0.6017831563949585),
 ('ne', 0.6013097167015076),
 ('waar', 0.594710648059845),
 ('moet', 0.5922201871871948),
 ('te', 0.5908597707748413),
 ('denne', 0.5897035598754883),
 ('naar', 0.5896697044372559),
 ('gaan', 0.5889247059822083)]

In [155]:
wv.most_similar('education')

[('eduction', 0.7980327010154724),
 ('eduation', 0.7175650000572205),
 ('LISA_MICHALS_covers', 0.6817380785942078),
 ('Matt_Krupnick_covers', 0.6798164248466492),
 ('educational', 0.678000807762146),
 ('educa_tion', 0.661638081073761),
 ('edu_cation', 0.6534408926963806),
 ('educations', 0.6410858035087585),
 ('professionals_CEC_SmartBrief', 0.6308876872062683),
 ('curriculum', 0.6266545653343201)]

In [157]:
wv.most_similar('indian')

[('india', 0.6967040300369263),
 ('american', 0.6599414944648743),
 ('indians', 0.6493048667907715),
 ('pakistani', 0.6424943208694458),
 ('british', 0.6309670209884644),
 ('chinese', 0.6180857419967651),
 ('sri_lankan', 0.6162428259849548),
 ('pakistan', 0.6157864332199097),
 ('malaysian', 0.602706789970398),
 ('tamil', 0.6002824306488037)]

In [158]:
wv.most_similar('Hindu')

[('Hindus', 0.7838510870933533),
 ('Sikh', 0.6908060908317566),
 ('Hinduism', 0.6554391384124756),
 ('Vaishnavite', 0.6438902020454407),
 ('Hindu_fundamentalist', 0.6376325488090515),
 ('rightwing_Hindu', 0.6299793720245361),
 ('Guru_Ravidass', 0.6258084774017334),
 ('Muslim', 0.6226926445960999),
 ('Hindu_fundamentalists', 0.6214293241500854),
 ('sikh', 0.6199694275856018)]

In [159]:
wv.most_similar('BJP')

[('Samajwadi_Party', 0.8747575283050537),
 ('RJD', 0.871252715587616),
 ('Bharatiya_Janata_Party', 0.8632032871246338),
 ('CPI_M', 0.858258068561554),
 ('JD_U', 0.8575517535209656),
 ('UPA', 0.8353379964828491),
 ('Mulayam', 0.8294427394866943),
 ('JD_S', 0.8213956356048584),
 ('DMK', 0.8201932907104492),
 ('Nitish_Kumar', 0.8185547590255737)]

In [165]:
vec = wv['modi'] + wv['Tata'] + wv['Reliance'] + wv['rich']
wv.most_similar([vec])

[('Reliance', 0.7896878123283386),
 ('Tata', 0.7583782076835632),
 ('Reliance_Industries', 0.6783670783042908),
 ('Tatas', 0.6754528880119324),
 ('RIL', 0.6713529825210571),
 ('Ambani', 0.664646327495575),
 ('Anil_Ambani', 0.6604036092758179),
 ('TATA', 0.6554300785064697),
 ('Bharti', 0.6534833908081055),
 ('Mukesh', 0.6437507271766663)]

In [156]:
vec = wv['india'] + wv['education'] + wv['system']
wv.most_similar([vec])

[('india', 0.7433088421821594),
 ('education', 0.589250385761261),
 ('system', 0.5695293545722961),
 ('america', 0.5655617117881775),
 ('pakistan', 0.5632794499397278),
 ('sytem', 0.5632182359695435),
 ('indian', 0.5361905694007874),
 ('punjab', 0.5309917330741882),
 ('eduction', 0.5308288335800171),
 ('canada', 0.529075562953949)]

In [151]:
wv.most_similar('sex')

[('sexual', 0.7694741487503052),
 ('oral_sex', 0.6738982796669006),
 ('sexual_intercourse', 0.6690444946289062),
 ('intercourse', 0.6402736902236938),
 ('anal_sex', 0.6372365951538086),
 ('sexual_encounters', 0.6306261420249939),
 ('Chastity_Bono_announces', 0.6105126738548279),
 ('prostitution', 0.5989327430725098),
 ('Sex', 0.5975605845451355),
 ('masturbation', 0.5959034562110901)]

In [141]:
wv.most_similar('Virat')

[('Sanath', 0.6505971550941467),
 ('Sachin', 0.6505815386772156),
 ('Sourav', 0.6439367532730103),
 ('Ranadeb', 0.643051266670227),
 ('Saurav', 0.6387004852294922),
 ('Laxman', 0.6353415250778198),
 ('Ganguly', 0.6286967396736145),
 ('Yuvraj', 0.625824511051178),
 ('Kanitkar', 0.6231240034103394),
 ('Chandana', 0.6186356544494629)]

In [133]:
#Comparing 2 objects

wv.similarity('man','women')

0.2883053

In [140]:
# Find odd in out
wv.doesnt_match(['tiger','lion','bottle','monkey'])

'bottle'

In [136]:
ans = (wv['king'] - wv['man']) + wv['women']
wv.most_similar([ans])

[('king', 0.6478992104530334),
 ('queen', 0.535493791103363),
 ('women', 0.52336585521698),
 ('kings', 0.5162314772605896),
 ('queens', 0.4995364844799042),
 ('kumaris', 0.492384672164917),
 ('princes', 0.46233269572257996),
 ('monarch', 0.4528028964996338),
 ('monarchy', 0.429317444562912),
 ('kings_princes', 0.42342400550842285)]

In [143]:
x = (wv['society'] - wv['movie']) + wv['education']
wv.most_similar([x])

[('education', 0.6813852787017822),
 ('society', 0.6670683026313782),
 ('eduction', 0.5541669130325317),
 ('eduation', 0.5490455031394958),
 ('societies', 0.49036842584609985),
 ('educa_tion', 0.48864564299583435),
 ('educational', 0.48538222908973694),
 ('ed_ucation', 0.481196790933609),
 ('Lifelong_learning', 0.4784870147705078),
 ('Educational_attainment', 0.47661200165748596)]

In [146]:
x = (wv['Man'] - wv['love']) 
wv.most_similar([x])

[('Man', 0.7344020009040833),
 ('Woman', 0.5112388134002686),
 ('Capri_Pacing_Series', 0.41140201687812805),
 ('Suspect', 0.4090985953807831),
 ('Robber', 0.39425453543663025),
 ('Assailant', 0.3806186318397522),
 ('Panhandler', 0.3780188262462616),
 ('Capri_Casinos_ISLE', 0.37684619426727295),
 ('Capri_ISLE', 0.37642166018486023),
 ('Shoplifter', 0.3727079927921295)]

In [149]:
x = (wv['Woman'] - wv['Man']) 
wv.most_similar([x])

[('Woman', 0.5213946104049683),
 ('she', 0.4338246285915375),
 ('Women', 0.4303523898124695),
 ('her', 0.4228554666042328),
 ('Businesswoman', 0.3960265517234802),
 ('Businesswomen', 0.38523033261299133),
 ('woman', 0.3851962983608246),
 ('Womens', 0.38073423504829407),
 ('Women_Entrepreneurs', 0.373238205909729),
 ('Unsung_Heroines', 0.3685576319694519)]

In [150]:
x = (wv['Man'] - wv['Woman']) 
wv.most_similar([x])

[('Malpede_senior', 0.29912400245666504),
 ('Greg_Gorbatenko_telecommunications', 0.2917774021625519),
 ('Uncle', 0.27213042974472046),
 ('Chelski', 0.2687279284000397),
 ('Mancs', 0.2666052579879761),
 ('frontmen', 0.2652149200439453),
 ('change.The', 0.2642357349395752),
 ('stickman', 0.255386620759964),
 ('jenas', 0.2551044225692749),
 ('analyst_Mamoun_Tazi', 0.25466635823249817)]

## TF-IDF

In [174]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer()

In [175]:
tv.fit_transform(df['text']).toarray() #Useful for IR(Information Retrieval)

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [176]:
print(tv.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]


In [177]:
print(tv.get_feature_names_out())

['comments' 'facebook' 'people' 'watch' 'write']
