## Minimum Edit Distance From Scratch

In [10]:
word1 = "INTENTION"
word2 = "EXECUTION"

In [11]:
length = len(word1)
length

9

In [12]:
count = 0
new1 = []
new2 = []
length = len(word1)-1


for i in range(length):
    if word1[length-i]==word2[length-i]:
        new1.append(word1[length-i])
        new2.append(word2[length-i])
    elif word1[length-i]==word2[length-i-1]:
        new1.append("*")
        new1.append(word1[length-i])
        new2.append(word2[length-i])
        count+=1
    else:
        new1.append(word1[length-i])
        new2.append(word2[length-i])
        
print(new1)
print(new2)

['N', 'O', 'I', 'T', 'N', '*', 'E', 'T', 'N']
['N', 'O', 'I', 'T', 'U', 'C', 'E', 'X']


In [13]:
w1 = "INTENTION"
word1 = list(w1)
w2 = "EXECUTION"
word2 = list(w2)
word1

['I', 'N', 'T', 'E', 'N', 'T', 'I', 'O', 'N']

In [5]:
w1 = "GEEXSFRGEEKKS"
word1 = list(w1)
w2 = "GEEKSFORGEEKS"
word2 = list(w2)
word1


count = 0
new1 = []
new2 = []
length = len(word1)-1


for i in range(length):
    
    if word1[length-i]==word2[length-i]:
        print(word1[length-i])
        print(word1)
        print(word2[length-i])
        print(word2)
        print(" ")
        continue
    elif word1[length-i]==word2[length-i-1]:
        word1.insert(length-i+1, "*")
        print(word1[length-i])
        print(word1)
        print(word2[length-i-1])
        print(word2)
        print(" ")
        count+=1
    # elif word1[length-i]!=word2[length-i]:
    #     print(word1)
    #     print(word2)
    #     print(" ")
    #     continue
for i in range(count):
    word2.insert(0, "*")
print(word1)
print(word2)

S
['G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
S
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S']
 
K
['G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
K
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S']
 
E
['G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
E
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S']
 
F
['G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
F
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S']
 
S
['G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
S
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S']
 
E
['G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
E
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S']
 
E
['G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
E
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S']
 
['G', 'E', 'E', 'X', 'S', 'F', 'R'

In [14]:
w1 = "GEEXSFRGEEKKS"
word2 = list(w1)
w2 = "GEEKSFORGEEKS"
word1 = list(w2)
word1


count = 0
new1 = []
new2 = []
length = len(word1)-1


for i in range(length):
    print(word1)
    print(word2)
    print(" ")
    if word1[length-i]==word2[length-i]:
        # print(word1[length-i])
        # print(word1)
        # print(word2[length-i])
        # print(word2)
        # print(" ")
        continue
    elif word1[length-i]==word2[length-i-1]:
        word1.insert(length-i+1, "*")
        word2.insert(0, "*")
        # print(word1[length-i])
        # print(word1)
        # print(word2[length-i-1])
        # print(word2)
        print(" ")
        count+=1
    elif word1[length-i]==word2[length-i+1]:
        word2.insert(length-i+2, "*")
        word1.insert(0, "*")
    # elif word1[length-i]!=word2[length-i]:
    #     print(word1)
    #     print(word2)
    #     print(" ")
    #     continue

print(word1)
print(word2)

['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S']
['G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
 
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S']
['G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
 
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S']
['G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
 
 
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', '*', 'K', 'S']
['*', 'G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
 
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', '*', 'K', 'S']
['*', 'G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
 
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', '*', 'K', 'S']
['*', 'G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
 
['G', 'E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', '*', 'K', 'S']
['*', 'G', 'E', 'E', 'X', 'S', 'F', 'R', 'G', 'E', 'E', 'K', 'K', 'S']
 
['G', 'E', 'E', 'K',

In [7]:
w1 = "INTENTION"
word1 = list(w1)
w2 = "EXECUTION"
word2 = list(w2)
word1


count = 0
new1 = []
new2 = []
length = len(word1)-1


for i in range(length):
    if word1[length-i]==word2[length-i]:
        # print(word1[length-i])
        # print(word1)
        # print(word2[length-i])
        # print(word2)
        # print(" ")
        continue
    elif word1[length-i]==word2[length-i-1]:
        word1.insert(length-i+1, "*")
        word2.insert(0, "*")
        # print(word1[length-i])
        # print(word1)
        # print(word2[length-i-1])
        # print(word2)
        print(" ")
        count+=1
    elif word1[length-i]==word2[length-i+1]:
        word2.insert(length-i+2, "*")
        word1.insert(0, "*")
    # elif word1[length-i]!=word2[length-i]:
    #     print(word1)
    #     print(word2)
    #     print(" ")
    #     continue
# for i in range(count):
#     word2.insert(0, "*")
print(word1)
print(word2)

 
['I', 'N', 'T', 'E', '*', 'N', 'T', 'I', 'O', 'N']
['*', 'E', 'X', 'E', 'C', 'U', 'T', 'I', 'O', 'N']


In [15]:
w1 = ['I', 'N', 'T', 'E', '*', 'N', 'T', 'I', 'O', 'N']
w2 = ['*', 'E', 'X', 'E', 'C', 'U', 'T', 'I', 'O', 'N']
dist = 0
for i in range(len(w1)-1):
    if w1[i]=="*":
        w1[i]=w2[i]
        dist+=1
    elif w2[i]=="*":
        w1[i]=w2[i]
        dist+=1
    elif w1[i]!=w2[i]:
        w1[i]=w2[i]
        dist+=2
        
for i in range(len(w1)-1):
    if w1[i]=="*" and w2[i]=="*":
        w1.pop(i)
        w2.pop(i)
print(w1)
print(w2)
print(dist)

['E', 'X', 'E', 'C', 'U', 'T', 'I', 'O', 'N']
['E', 'X', 'E', 'C', 'U', 'T', 'I', 'O', 'N']
8


In [21]:
import numpy as np

def min_edit_dist(str1, str2):
    n = len(str1)
    m = len(str2)
    dp = [[0 for _ in range(m+1)] for _ in range(n+1)]
    # dp = np.zeros((n+1, m+1), dtype=int)

    for i in range(1, n+1):
        dp[i][0] = i
    for j in range(1, m+1):
        dp[0][j] = j

    for i in range(1, n+1):
        for j in range(1, m+1):
            if str1[i-1] == str2[j-1]:
                dp[i][j] = dp[i-1][j-1]  
            else:
                insertion = dp[i][j-1] + 1
                deletion = dp[i-1][j] + 1
                if str1[i-1] == str2[j-1]:       
                    substitution = dp[i-1][j-1]+0
                else:
                    substitution = dp[i-1][j-1]+2
                dp[i][j] = min(insertion, deletion, substitution) 
 
    print("Edit Distance Matrix:")
    for row in dp:
        print(row)
    return dp

wo1 = "INTENTION"
wo2 = "EXECUTION"
output = min_edit_dist(wo1, wo2)

Edit Distance Matrix:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 6, 7, 8]
[2, 3, 4, 5, 6, 7, 8, 7, 8, 7]
[3, 4, 5, 6, 7, 8, 7, 8, 9, 8]
[4, 3, 4, 5, 6, 7, 8, 9, 10, 9]
[5, 4, 5, 6, 7, 8, 9, 10, 11, 10]
[6, 5, 6, 7, 8, 9, 8, 9, 10, 11]
[7, 6, 7, 8, 9, 10, 9, 8, 9, 10]
[8, 7, 8, 9, 10, 11, 10, 9, 8, 9]
[9, 8, 9, 10, 11, 12, 11, 10, 9, 8]


In [32]:
import numpy as np

def min_edit_dist(s1, s2):
    n = len(s1)
    m = len(s1)
    # dp = [[0 for _ in range(m+1)] for _ in range(n+1)]
    dp = np.zeros((n+1, m+1), dtype=int)

    for i in range(1, n+1):
        dp[i][0] = i
    for j in range(1, m+1):
        dp[0][j] = j

    for i in range(1, n+1):
        for j in range(1, m+1):
            if s1[i-1] == s2[j-1]:
                dp[i][j] = dp[i-1][j-1]  
            else:
                insertion = dp[i][j-1] + 1
                deletion = dp[i-1][j] + 1
                if s1[i-1] == s2[j-1]:       
                    substitution = dp[i-1][j-1]+0
                else:
                    substitution = dp[i-1][j-1]+2
                dp[i][j] = min(insertion, deletion, substitution) 
 
    print("Edit Distance Matrix:")
    rotated_dp = np.rot90(dp, k=1)
    print(rotated_dp)
    

wo1 = "INTENTION"
wo2 = "EXECUTION"
output = min_edit_dist(wo1, wo2)

Edit Distance Matrix:
[[ 9  8  7  8  9 10 11 10  9  8]
 [ 8  7  8  9 10 11 10  9  8  9]
 [ 7  6  7  8  9 10  9  8  9 10]
 [ 6  7  8  7  8  9  8  9 10 11]
 [ 5  6  7  8  7  8  9 10 11 12]
 [ 4  5  6  7  6  7  8  9 10 11]
 [ 3  4  5  6  5  6  7  8  9 10]
 [ 2  3  4  5  4  5  6  7  8  9]
 [ 1  2  3  4  3  4  5  6  7  8]
 [ 0  1  2  3  4  5  6  7  8  9]]
